---
name: housekeeping

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
    # paths:
    #   - "contents/docs/*"
    #   - "contents/mkdocs.yml"

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: "**/*.md"

  spellchecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code

      - uses: actions/setup-node@v1
        name: Run spell check
        with:
          node-version: "14"

      - run: npm install -g cspell
      - run: cspell --config ./cSpell.json --no-progress "**/*.md"
